### ISSUE TITLE
Object has no method 'convertCompilerOptionsFromJson'

### ISSUE THREAD

**Issue by richard-w** [joost-de-vries/sbt-typescript#2] opened 2016-04-03 18:42 UTC
I encounter the following error for all examples you provide (in this case play-angular-typescript):

```
com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: 
/home/richard/src/play-angular2-typescript/target/typescript/typescript.js:191
        return ts.convertCompilerOptionsFromJson(unparsedCompilerOptions, sbtO
                  ^
TypeError: Object #<Object> has no method 'convertCompilerOptionsFromJson'
    at toCompilerOptions (/home/richard/src/play-angular2-typescript/target/typescript/typescript.js:191:19)
    at compile (/home/richard/src/play-angular2-typescript/target/typescript/typescript.js:152:14)
    at Object.<anonymous> (/home/richard/src/play-angular2-typescript/target/typescript/typescript.js:146:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

    at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:195)
    at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:167)
    at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
    at scala.util.Try$.apply(Try.scala:161)
    at scala.util.Success.map(Try.scala:206)
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
    at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by joost-de-vries** [comment] 2016-04-04 18:11
From this error I'm guessing that you have an older version of Typescript installed globally.
The sbt-typescript plugin uses node resolution of typescript. De-install the global version of typescript and sbt-typescript should find the correct version. 
This is a duplicate of [this issue](https://github.com/joost-de-vries/play-angular2-typescript/issues/1).
I'll update the readmes to make this more clear.

**Comment by joost-de-vries** [comment] 2016-04-05 14:27
Let me know if this does not solve your issue. Otherwise I'll close this.

**Comment by richard-w** [comment] 2016-04-07 21:01
There was in fact a local typescript installation in my home. Removing it solved the problem. Thank you.

I still think this is a bug. If sbt-typescript relies on a specific version of typescript it should take care that this version is in fact there. An error-message would help too. It is very surprising that local npm installations interfere with sbt builds.

**Closed as completed** 2016-04-08 15:36 UTC
